### ISSUE TITLE
Module names aren't highlighting

### ISSUE THREAD

**Issue by maco** [elixir-lang/tree-sitter-elixir#15] opened 2021-12-15 20:19 UTC
tree-sitter-elixir was pushed live on GitHub today 🎉  , but @the-mikedavis pointed out that module names aren't highlighting
Example: https://github.com/elixir-mint/mint/blob/1ea7731d921840ad75a47fa9415525c3d94b9980/mix.exs#L1-L2

![Screen Shot 2021-12-15 at 3 15 32 PM](https://user-images.githubusercontent.com/401264/146258759-822dafb4-0157-41ed-ad11-7d7533d86506.png)

Example 2: https://github.com/elixir-mint/mint/blob/1ea7731d921840ad75a47fa9415525c3d94b9980/lib/mint/http1.ex#L108-L113
![Screen Shot 2021-12-15 at 3 16 09 PM](https://user-images.githubusercontent.com/401264/146258760-b8367664-10e5-47f8-8ded-5882a3704834.png)

CC @patrickt (who asked to be CC'd so he can push an updated grammar on GitHub's end when this is handled.)

**Comment by jonatanklosko** [comment] 2021-12-15 20:26
Hey! Modules are highlighted correctly for me when running tree-sitter highlighter locally:

![image](https://user-images.githubusercontent.com/17034772/146259926-ca2720a7-8084-41cf-966b-a16002717aa6.png)

This is probably related to the theme GitHub uses? The modules get the `type` highlight token, should we be using something else?

**Comment by the-mikedavis** [comment] 2021-12-15 20:29
From what I can tell it looks like these highlights aren't ending up syntax-highlighted to any color: https://github.com/elixir-lang/tree-sitter-elixir/blob/de3ec57591aebf451e710fc9c984cf601258baf5/queries/highlights.scm#L65-L69

which is curious because the java queries for example use `@type` as well: https://github.com/tree-sitter/tree-sitter-java/blob/ed3a87f750b1d1d533f15ab93fef3e1f5a46e234/queries/highlights.scm#L22-L23, and I assume java is tree-sitter highlighted in github, and I see class names highlighted as I would expect (e.g. [here](https://github.com/json-iterator/java/blob/e48a7a1958f5f99ceb2a419d88e92131843388b1/src/main/java/com/jsoniter/spi/Slice.java#L3))

Maybe it's just a precedence issue? Or maybe github also needs a `tags.scm` to identify clasess/modules?

**Comment by jonatanklosko** [comment] 2021-12-15 20:43
Without `@type` the module name doesn't get any highlighting token, so there should be no conflict either way :thinking:

The module name gets the `pl-smi` class instead of `pl-en`.

**Comment by the-mikedavis** [comment] 2021-12-15 21:58
Ah good find: seems like the problem isn't with the grammar/queries here but something in how GitHub is mapping the tree-sitter scopes to class names. I'm not sure how to get the ball rolling with GitHub support on this. Maybe we can re-use the contact mentioned in [#2 (comment)](https://github.com/elixir-lang/tree-sitter-elixir/issues/2#issuecomment-995058337) (cc: @josevalim)?

**Comment by patrickt** [comment] 2021-12-15 21:59
Yeah, I don’t think `@type` is quite right here. I’m trying to figure this out (and will assemble some docs, hopefully).

**Comment by jonatanklosko** [comment] 2021-12-15 21:59
The tests for Java tree-sitter highlighting are in [this file](https://github.com/tree-sitter/tree-sitter-java/blob/ed3a87f750b1d1d533f15ab93fef3e1f5a46e234/test/highlight/types.java) and it confuses me because tokens annotated as `type` are highlighted with three different colors. This would only make sense if for some reason tree-sitter is not used for highlighting Java files.

Looking at similar tests for [JavaScript](https://github.com/tree-sitter/tree-sitter-javascript/blob/fdeb68ac8d2bd5a78b943528bb68ceda3aade2eb/test/highlight/variables.js) and [Ruby](https://github.com/tree-sitter/tree-sitter-ruby/blob/888e2e563ed3b43c417f17e57f7e29c39ce9aeea/test/highlight/classes.rb), it looks like modules/classes use the `constructor` token, which doesn't seem suitable in our case.

**Comment by patrickt** [comment] 2021-12-15 22:01
@jonatanklosko Correct: I just found out that tree-sitter-java’s highlights aren’t hitting prod traffic, so a better comparison is Python or Ruby in their respective repositories. Apologies for the confusion.

**Comment by jonatanklosko** [comment] 2021-12-15 22:03
Is the mapping/theme a part of some open source project or is it something you maintain internally?

**Comment by patrickt** [comment] 2021-12-15 22:04
Hang on a sec, I’m gonna write up a Markdown table.

**Comment by patrickt** [comment] 2021-12-15 22:07
It’s closed-source. I’m dotting my i’s properly and checking to make sure I can give you the whole list without running awry of lawyers. But yes, @type maps to the `pl-smi` class, which doesn’t appear to be used. I would try `constructor` for the time being; I know it doesn’t exactly match the semantics, but mapping `@type` to something colorable will be a more protracted process.

**Comment by patrickt** [comment] 2021-12-15 22:14
@jonatanklosko Actually, I think I can get that `@module` change in pretty fast. So change those `@type` to `@module` and I’ll coordinate on my backend.

**Comment by jonatanklosko** [comment] 2021-12-15 22:15
Fantastic!

**Comment by patrickt** [comment] 2021-12-15 22:21
Okay, the changes required to recognize `@module` in syntax highlighting in our backend are coming in and should be deployed in the next fifteen minutes or so. Once #16 lands, I’ll bump the submodule in our backend, and deploy again. Thanks all for your patience.

**Comment by jonatanklosko** [comment] 2021-12-15 22:31
Beautiful, thanks for all the help! I've just merged the change, so we should be good on this side :D

**Comment by patrickt** [comment] 2021-12-15 22:52
This is working now: 
<img width="522" alt="image" src="https://user-images.githubusercontent.com/2498/146277140-e59a88cc-6dd4-47fe-b2c1-292c2904e80b.png">

**Comment by jonatanklosko** [comment] 2021-12-15 22:55
Awesome, thanks! :shipit:

The examples linked in the issue description are still the same, is that caching temporary?

**Comment by patrickt** [comment] 2021-12-15 22:56
@jonatanklosko Yeah, I think that’s memcached doing its thing. It’ll fall out of cache eventually, heh!

**Comment by jonatanklosko** [comment] 2021-12-15 22:56
Perfect :D

**Closed by jonatanklosko** 2021-12-15 22:56 UTC
